server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

spring:
  application:
    name: djs-zuul-depart


#设置路由规则
zuul:
  routes:
    my.serviceId: djs-consumer-depart
    my.path: /djsconsumer/**
  #ignored-services: djs-consumer-depart   #指定要忽略的微服务名称
  prefix: yd    #访问的前缀

